[package]
name = "cygnus"
version = "0.1.0"
authors = ["swan_of_bodom <@0xhyoga>"]
license = "MIT"
keywords = ["starknet", "defi", "lending", "stablecoins", "lps"]
description = "Decentralized stablecoin lending for Liquidity Providers"
documentation = "https://docs.cygnusdao.finance"
homepage = "https://cygnusdao.finance"
repository = "https://github.com/CygnusDAO"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true

[cairo]
sierra-replace-ids = true

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.13.0" }
starknet = "2.4.2"

[[tool.snforge.fork]]
name = "MAINNET"
url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_6"
block_id.number = "501900" # Latest

[tool.snforge]
exit_first = true

[tool.fmt]
max-line-length = 120

